package com.medlab.medlabtest.utils

object Properties {
    val BUNDLE_KEY_INSTRUCTABLE = "BUNDLE_KEY_INSTRUCTABLE"
    val BUNDLE_QUERY_PARAMS = "BUNDLE_QUERY_PARAMS"
    val BUNDLE_KEY_CATEGORY = "BUNDLE_KEY_CATEGORY"
    val BUNDLE_KEY_AUTHOR = "BUNDLE_KEY_AUTHOR"
    val BUNDLE_LIST_TITLE = "BUNDLE_LIST_TITLE"

    val EXTRA_GLEAMIO_ITEM = "EXTRA_GLEAMIO_ITEM"

    val QUERY_KEY_INSTRUCTABLE = "id"

    val WS_SORT_KEY = "sort"
    val WS_KEY_TYPE = "type"
    val WS_CATEGORY = "category"
    val WS_CHANNEL = "channel"
    val WS_QUERY = "search"
    val WS_KEY_OFFSET = "offset"
    val WS_KEY_LIMIT = "limit"
    val WS_FEATURED = "featured"
    val WS_TYPE_ID = "id"
    val WS_RECENT = "recent"
    val WS_POPULAR = "popular"
    val WS_FEATURED_HOME_PAGE = "featuredHomePage"

    const val FIREBASE_ADDED_AT_TEXT = "addedAt"
    const val FIREBASE_DATA_END_TEXT = "dataEnd"
    const val FIREBASE_DATA_START_TEXT = "dataStart"

    const val FIREBASE_ADDED_AT = 0
    const val FIREBASE_DATA_END = 1
    const val FIREBASE_DATA_START = 2

    const val FIREBASE_CHILD_ITEMS = "items"
    const val FIREBASE_CHILD_GIVEAWAYS = "giveaways"

    const val ORDER_DESCENDING = 0
    const val ORDER_ASCENDING = 1

    val ITEMS_PER_PAGE = 20
    val ADS_PER_PAGE = 2
    val ADS_POSITION_IN_PAGE = ITEMS_PER_PAGE / ADS_PER_PAGE
    val TIMES_DETAIL_INTERSTITIAL_AD = 10
    val ITEMS_PER_SWIMLANE = 7

    val FRAGMENT_TAG_CHANNEL = "FRAGMENT_TAG_CHANNEL"
    val FRAGMENT_TAG_CATEGORY = "FRAGMENT_TAG_CATEGORY"
    val FRAGMENT_TAG_HOME = "FRAGMENT_TAG_HOME"
    val FRAGMENT_TAG_LIST_SEARCH = "FRAGMENT_TAG_LIST_SEARCH"
    val FRAGMENT_TAG_LIST_HOME = "FRAGMENT_TAG_LIST_HOME"
    val FRAGMENT_TAG_INTERSTITIAL_AD = "FRAGMENT_TAG_INTERSTITIAL_AD"

    val THROWABLE_MAX_FAV = "THROWABLE_MAX_FAV"

    val FILE_ITEM_TYPE_IMAGE = 1
    val FILE_ITEM_TYPE_VIDEO = 2
    val FILE_ITEM_TYPE_YOUTUBE = 3
    val FILE_ITEM_TYPE_ARDUINO = 4
    val FILE_ITEM_TYPE_BOARD = 5
    val FILE_ITEM_TYPE_ZIP = 6
    val FILE_ITEM_TYPE_GIF = 7
    val FILE_ITEM_TYPE_PDF = 8
    val FILE_ITEM_TYPE_OTHER = 9
    val FILE_ITEM_TYPE_RAR = 10

    val LIST_TYPE_POPULAR = 1
    val LIST_TYPE_RECENT = 2
    val LIST_TYPE_FEATURED = 3
    val LIST_TYPE_HOMEFEATURED = 4
}

